all: pipe pipe2 pipe3

pipe: pipe_buf_size.c
	gcc -Wall -Wextra pipe_buf_size.c -o psz

pipe2: pipe_buf_size2.c
	gcc -Wall -Wextra pipe_buf_size2.c -o psz2

pipe3: pipe_buf_size3.c
	gcc -Wall -Wextra pipe_buf_size3.c -o psz3 -pthread